config/routes.rb
VarnaLab::Application.routes.draw do
  devise_for :users

  namespace :admin do
    root :to => 'pages#index'
    resources :pages
    resources :events

    match '/page/:page_id/comments/(:review)', :to => 'comments#index', :as => 'page_comments'
    
    resources :users, :controller => 'users' do
      match '/users/index', :to => 'users#index', :as => '', :on => :collection, :constraints => { :index => /[a-z]+/ }
    end
    
    resources :comments, :only => [:destroy] do
      post :review, :to => 'comments/reviews#create'
      delete :review, :to => 'comments/reviews#destroy'

     match '/(:review)', :to => 'comments#index', :as => '', :on => :collection, :constraints => { :review => /[a-z]+/ }
    end
  end

  resources :pages, :only => [:show] do
    resources :comments, :only => [:create]
  end

  root :to => 'pages#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, :polymorphic => true

  validates_presence_of :commenter_name, :commenter_email, :commentable, :body
  validates_format_of :commenter_email, :with => /.+@.+\.\w+/

  attr_protected :hidden, :reviewed

  scope :hidden, where(:hidden => true)
  scope :visible, where(:hidden => false)
  scope :unreviewed, where(:reviewed => false)

  def review_with!(approved)
    self.hidden = !approved
    self.reviewed = true
    save!
  end

  module Commentable
    def self.included(base)
      base.has_many :comments, :as => :commentable
    end

    def build_comment(attributes = {})
      raise "You can't comment on uncommentable entry" unless commentable?
      comments.build(attributes)
    end

    def visible_comments
      comments.visible
    end

    def visible_comments_count
      visible_comments.count
    end
  end
end

app/controllers/admin/comments/hide_controller.rb
class Admin::Comments::HideController < Admin::BaseController
  def create
    find_comment.review_with! false

    redirect_to admin_comments_path, :notice => 'The comment was successfully hidden'
  end

  def destroy
    find_comment.review_with! true

    redirect_to admin_comments_path, :notice => 'The comment was successfully marked as visible'
  end

  private

  def find_comment
    Comment.find(params[:comment_id])
  end
end

app/controllers/admin/comments/reviews_controller.rb
class Admin::Comments::ReviewsController < Admin::BaseController
  def create
    find_comment.review_with! true

    redirect_to :back, :notice => 'The comment was successfully marked as visible'
  end

  def destroy
    find_comment.review_with! false

    redirect_to :back, :notice => 'The comment was successfully hidden'
  end

  private

  def find_comment
    Comment.find(params[:comment_id])
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::BaseController
  
  def index
    @presenter = Admin::CommentsPresenter.new(presenter_options)
  end

  def destroy
  	comment = Comment.find(params[:id])
  	comment.destroy
  	redirect_to :back, :notice =>"Comment destroyed succesfully"
  end
  		
  private

  def presenter_options
    options = {:review => params[:review]}
    options[:commentable] = Page.find(params[:page_id]) if params[:page_id].present?
    options
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @page = find_page(params[:page_id])
    @comment = @page.build_comment(params[:comment])

    if @comment.save
      redirect_to page_path(@page, :anchor => dom_id(@comment))
    else
      render :template => 'pages/show'
    end
  end
end

app/helpers/admin/comments/review_helper.rb
module Admin::Comments::ReviewHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
  def unreviewed_comments_badge
    count = Comment.unreviewed.count

    options = {:id => 'unreviewed-comments-count', :title => pluralize(count, 'unreviewed comment')}
    options[:style] = 'display:none' if count == 0

    content_tag :spam, count, options
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def new_comment_form_for(commentable, &block)
    form_id = 'new-comment'
    comment = @comment || Comment.new
    url = page_comments_path(commentable, :anchor => form_id)

    simple_form_for comment, :url => url, :html => {:id => form_id}, &block
  end
end

app/views/admin/comments/index.html.slim
header
  = link_to 'All', admin_comments_path if params[:review].present?
  h1 = title @presenter.title
  nav
    = link_to 'Unreviewed', unreviewed_admin_comments_path
    = link_to 'Visible', visible_admin_comments_path
    = link_to 'Hidden', hidden_admin_comments_path

#comments-list
  - @presenter.comments.each do |comment|
    section
      header
        | ##{comment.id} - #{link_to comment.commentable.name, [:admin, comment.commentable]}
        time = time_ago_in_words(comment.created_at) + ' ago'
        .actions
          - if comment.hidden?
            = link_to 'Show', admin_comment_review_path(comment), :method => :post, :confirm => 'Are you sure?', :title => "Show comment ##{comment.id}"
            = link_to 'Delete', admin_comment_path(comment), :method => :delete, :confirm => 'Are you sure?', :title => "Delete this comment ##{comment}"
          - elsif comment.reviewed?
            = link_to 'Hide', admin_comment_review_path(comment), :method => :delete, :confirm => 'Are you sure?', :title => "Hide comment ##{comment.id}"
          - else
            = link_to 'Approve', admin_comment_review_path(comment), :method => :post, :confirm => 'Are you sure?', :title => "Approve comment ##{comment.id}"
            = link_to 'Hide', admin_comment_review_path(comment), :method => :delete, :confirm => 'Are you sure?', :title => "Hide comment ##{comment.id}"
            
      .body
        - if comment.hidden?
          .hidden-marker
        = simple_format comment.body
      footer
        strong = comment.commenter_name
        em = comment.commenter_email

= paginate @presenter.comments