config/routes.rb
VarnaLab::Application.routes.draw do
  devise_for :users

  namespace :admin do
    root :to => 'pages#index'
    resources :pages
    resources :events

    match '/page/:page_id/comments/(:review)', :to => 'comments#index', :as => 'page_comments'
    
    resources :users, :controller => 'users' do
      match '/users/index', :to => 'users#index', :as => '', :on => :collection, :constraints => { :index => /[a-z]+/ }
    end
    
    resources :comments, :only => [:destroy] do
      post :review, :to => 'comments/reviews#create'
      delete :review, :to => 'comments/reviews#destroy'

     match '/(:review)', :to => 'comments#index', :as => '', :on => :collection, :constraints => { :review => /[a-z]+/ }
    end
  end

  resources :pages, :only => [:show] do
    resources :comments, :only => [:create]
  end

  root :to => 'pages#index'
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :author
  attr_accessible :body, :date, :place, :title
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::BaseController
	
	before_filter :authenticate_user!
  inherit_resources

  actions :show, :new, :create, :update, :edit, :destroy

	def index
	  @events = Event.all
	end

	def show
  	  @event = Event.find(params[:id])
	end
  def destroy
    destroy! :flash => !request.xhr?
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/_event.html.slim
li
  = link_to event.title, [:admin, event]
  .actions
    = link_to_edit event
    = link_to_delete event

app/views/admin/events/_form.html.slim
= simple_form_for [:admin, @event] do |form|
  = form.error_notification
  fieldset
    = form.input :title
    = form.input :date
    = form.input :place
    = form.input :body
  .buttons
    = form.button :submit

app/views/admin/events/index.html.slim
header
  h1 = title 'Events'
  nav = link_to 'Create a new event', new_admin_event_path

ul#grid = render @events

app/views/admin/events/new.html.slim
header
  = link_to_cancel admin_events_path
  h1 = title 'New event'

= render 'form'

app/views/admin/events/show.html.slim
header
  h1 = title @event.title
  nav
    //= link_to_comments_of @event //TODO make events to have comments
    = link_to_edit @event
    = link_to_delete @event, :remote => false

  .content = simple_format @event.date
    @event.place  
    @event.body